services:
  backend:
    build:
      context: ./backend/belicos_backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://belicosUser:Belicos@Senha007@db:5432/belicosDB
    ports:
      - "8001:8000" # Backend exposed on port 8000
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: belicosUser
      POSTGRES_PASSWORD: Belicos@Senha007
      POSTGRES_DB: belicosDB
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend

volumes:
  db_data:
