services:
  backend:
    build:
      context: ./backend/belicos_backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://belicosUser:Belicos@Senha007@db:5432/belicosDB
    ports:
      - 8000:8000 # Backend exposed on port 8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: belicosUser
      POSTGRES_PASSWORD: Belicos@Senha007
      POSTGRES_DB: belicosDB
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend

volumes:
  db_data:
